name: PR
# To test fastlane build commands on your local machine, install fastlane.
# sudo gem install fastlane -NV
#

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
env:
  RELEASE: release
  
jobs:
 
  # Run unit tests
  unit-tests:
    name: Build and run unit tests
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest] # 
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 15
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Checkout submodules
      run: |
        echo Checkout submodules
        #git fetch origin
        git submodule sync
        git submodule update --init --recursive 

    - name: Cleanup from last time
      if: (matrix.platform == 'self-hosted') 
      run: 
        rm -rf build

    - name: Build unit tests (posix)
      if: (matrix.platform != 'windows-latest')
      run: |
        mkdir build
        pushd build
        cmake ..
        make -j4
        popd

    # msbuild sweet_osal_platform.sln /property:Configuration=Debug -maxcpucount:4
    - name: Build unit tests (windows)
      if: (matrix.platform == 'windows-latest')
      run: |
        .\scripts\win_build.bat

    - name: Run unit tests.
      if: (github.workflow != 'CD')
      run: |
        cd build
        ctest -j4
        cd ..
  
